require('mini.comment').setup()
require('mini.completion').setup()
require('mini.cursorword').setup()
require('mini.pairs').setup({modes = {'c', 'i', 't'}})
require('mini.statusline').setup()
require('mini.surround').setup()
require('mini.tabline').setup()
require('mini.trailspace').setup()
