name: Test 'mini.git'

on: [push]

jobs:
  build:
    name: Test 'mini.git'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        neovim_version: ['v0.7.2', 'v0.8.3', 'v0.9.5', 'nightly']

    steps:
      - uses: actions/checkout@v4
      - name: Setup neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim_version }}
      - name: Run tests
        run: make test_git
